### PR TITLE
Update Cleanup SD Card and add Deleting Friendlist

### PR DESCRIPTION
**Pull request by Validusername16**
I was referred here by d0k3 to make these additions first after making a pull request on GodMode9's repository (https://github.com/d0k3/GodMode9/pull/468 ).

### CODE REVIEW

**Comment by eip618** [comment]
context: valid and i are helpers on nintendo homebrew, which sees a lot of users come through. the files added to the script are common setup files from latest *miner methods. the script also changes the handling of the cias folder to deleting the contents of the folder, as there is no reason (?) to delete the whole folder when it could be used for later organisation of cias

**Comment by annson24** [comment]
Hi. I'll review this later. I've been busy this last month and wasn't able to check.

**Comment by d0k3** [comment]
@eip618 - don't forget to add your pull request here, too.

**Comment by eip618** [comment]
I had Valid include my additions in their existing PR so as not to clutter the repo with stuff.

**Comment by d0k3** [comment]
Okay, thanks a lot!

**Comment by annson24** [comment]
The code looks absolutely clean, I know this is going to work without issue but for the sake of maintaining d0k3's trust I'll have to actually test this first to be extra sure. The thing is I already gave my 3ds away and am focusing on the switch now. Nevertheless, I can still remotely test this one but will take at least a day or two...hmm..I think I need to buy me another 3ds.

**Comment by d0k3** [comment]
Thanks, @annson24 - I really appreciate this.

**Comment by eip618** [comment]
There's just one thing we're yet to add to this PR in specific, which is cia folder handling - valid should merge my PR to his fork, and then this PR should update.

**Comment by eip618** [comment]
For what it's worth, some of this code was contributed by @Frozenfire, but they didn't say if they want credit.

**Comment by annson24** [comment]
Code tested and working.

**Pull request merged**
